config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :categories do
    resources :tasks
  end

  root 'tasks#today'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true,
                     uniqueness: true
    validates :description, presence: true

    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    validates :name, presence: true
    validates :details, presence: true

    belongs_to :category
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!

    def index
        @categories = Category.all 
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)

        if @category.save
            redirect_to categories_path
        else
            render :new
        end
    end

    def show
        @category = Category.find(params[:id])
        @tasks = Task.where(category_id: @category.id, user_id: current_user.id)
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])

        if @category.update(category_params)
            redirect_to categories_path
        else
            render :edit
        end
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to categories_path
    end

    private
    def category_params
        params.require(:category).permit(:name, :description)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :get_category
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    
    def index
        @tasks = Task.where(user_id: current_user.id).order(deadline: :desc)
    end

    def today
        @tasks_incomplete = Task.where(user_id: current_user.id, completed: false, deadline: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).order(deadline: :desc)
    end
   
    def new
        @task = @category.tasks.build
    end

    def create
        @task = @category.tasks.build(task_params)
        @task.user = current_user

        if @task.save
            redirect_to category_tasks_path
        else
            render :new
        end
    end

    def show
        
    end

    def edit
        
    end

    def update
        

        if @task.update(task_params)
            redirect_to category_tasks_path
        else
            render :edit
        end
    end

    def destroy
        
        @task.destroy
        redirect_to category_tasks_path
    end

    private
    def get_category
        
        # @category = Category.find(params[:category_id]) if params[:category_id].present?
        if params[:category_id]
            @category = Category.find(params[:category_id])
        end
        
    end

    def set_category
        @task = @category.tasks.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:name, :details, :deadline, :completed, :started, :category_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/edit.html.erb
<div class = "columns is-centered">
    <div class = "column is-half">
        <h1 class = "is-size-2 has-text-weight-bold mb-3">Edit Category</h1>

		<%= form_with model: @category, local: true do |f| %>
    		<p>
        		<% if @category.errors.any? %>
            		<ul>
                		<% @category.errors.full_messages.each do |message| %>
                    		<li style = "color: red">
                        		* <%= message%>
                    		</li>
                		<% end %>
            		</ul>
        		<% end %>
            </p>
            <br>
    		<div class = "field">
                <div class = "control">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: "input" %>
                </div>
            </div>

            <div class = "field">
                <div class = "control">
                    <%= f.label :description %>
                    <%= f.text_field :description, class: "input" %>
                </div>
            </div>
            <br>

            <div class = "field">
                <div class = "control">
                    <%= f.submit :Submit, class: "button is-success" %>
                    <%= link_to 'Back to Categories', categories_path, class: "button" %>
                </div>
            </div>
		<% end %>
	</div>  
</div>

app/views/categories/index.html.erb
<div class = "columns is-centered">
	<div class = "column is-half">
		<div class = "content">
			<h1 class = "is-size-2 has-text-weight-bold mb-3">Categories</h1>
			
			<br>
			<%= link_to 'Add a Category', new_category_path(@category),  class: 'button is-info' %>
		</div>
    
		<div class = "container">
			<table class = "table is-striped is-bordered is-fullwidth">
    			<thead>
        			<tr class="th is-selected">
            
            			<th>Category</th>
            			<th>Description</th>
            			<th>Actions</th>
        			</tr>
    			</thead>

    			<tbody>
        			<% @categories.each do |category| %>
            		<tr>
                
						<td><%= link_to category.name, category_path(category) %></td>
                		<td><%= category.description %></td>
                		<td>
                    		<%= link_to 'Edit', edit_category_path(category), class: "button is-small is-warning" %>
                    		<%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-small is-danger" %>
                		</td>
            		</tr>
        			<% end %>
    			</tbody>
			<table>
		</div>
	</div>
</div>

app/views/categories/new.html.erb
<div class = "columns is-centered">
    <div class = "column is-half">
        <h1 class = "is-size-2 has-text-weight-bold mb-3">New Category</h1>

		<%= form_with model: @category, local: true do |f| %>
            <p>
                <% if @category.errors.any? %>
                    <ul>
                        <% @category.errors.full_messages.each do |message| %>
                            <li style = "color: red">
                                * <%= message%>
                            </li>
                        <% end %>
                    </ul>
                <% end %>
            </p>
            <br>

            <div class = "field">
                <div class = "control">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: "input" %>
                </div>
            </div>

            <div class = "field">
                <div class = "control">
                    <%= f.label :description %>
                    <%= f.text_field :description, class: "input" %>
                </div>
            </div>
            <br>

            <div class = "field">
                <div class = "control">
                    <%= f.submit :Submit, class: "button is-success" %>
                    <%= link_to 'Back to Categories', categories_path, class: "button" %>
                </div>
            </div>
    
		<% end %>
	</div>
</div>

app/views/categories/show.html.erb
<div class = "columns is-centered">
    <div class = "column is-two-thirds">

		<h1 class = "is-size-2 has-text-weight-bold mb-3"><%= @category.name %></h1>
		
		
        
        <div class = "content">
			<%= @category.description %>
			<br>
			<br>
			<%= link_to 'Create Task', new_category_task_path(@category), class: "button is-info" %>
        </div>		
		
		

		<div class = "container">
			<table class = "table is-striped is-bordered is-fullwidth">
    			<thead>
        			<tr class="th is-selected">
            			<th>Name</th>
            			<th>Details</th>
            			<th>Deadline</th>
            			<th>Started</th>
            			<th>Completed</th>
            			<th>Actions</th>
        			</tr>
    			</thead>

    			<tbody>
        			<% @tasks.each do |task| %>
            
            			<tr>
                
                			<td><%= link_to task.name, [@category, task] %></td>
                			<td><%= task.details %></td>
                			<td><%= task.deadline %></td>
                			<td><%= task.started %></td>
                			<td><%= task.completed %></td>
                			<td>
                    			<div class = "field is-grouped">
                    				<div class = "control">
                            			<%= link_to 'Edit', edit_category_task_path(@category, task), class: "button is-small is-warning" %>
                        			</div>
                        			<div class = "control">
									<%= link_to 'Delete', [@category, task], method: :delete, data: {confirm: "Are you sure?"}, class: "button is-small is-danger" %>
                        			</div>
                    			</div>
                			</td>
            			</tr>
            
        			<% end %>
    			</tbody>
			<table>
			<%= link_to 'Back to Categories', categories_path, class: "button" %>
		</div>

	</div>
</div>

app/views/layouts/_alerts.html.erb
<div class = "columns is-centered">
    <div class = "column is-two-thirds">
        
        <p class="notice" style = "color: green"><%= notice %></p>
        <p class="alert" style = "color: red"><%= alert %></p>
        
    </div>
</div>

app/views/layouts/_header.html.erb
<section class="hero is-primary">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          
          <% if current_user %>
            <%= link_to 'Home', root_path, class: 'navbar-item' %>            
            <%= link_to 'Categories', categories_path, class: 'navbar-item' %>
                   
          <% else %>
            
            <%= link_to('Login', new_user_session_path, class: 'navbar-item' ) %>  
            
          <% end %>
            
          </a>
        </div>

        <div class="navbar-end">

            <% if current_user %>
              
              <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'navbar-item' ) %>
            <% end %>

        </div>

      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered", style = "margin-top: -50px;">
      <h1 class="title">
        Everyday Journal
      </h1>
      <h2 class="subtitle">
        Plan and organize your tasks
      </h2>
      
      
    </div>
  </div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = container style="max-width: 100%; margin: 50px;">
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class = "columns is-centered">
    <div class = "column is-half">
        <h1 class = "is-size-2 has-text-weight-bold mb-3">Edit Task</h1>
        
        <%= form_with model: [@category, @task], local: true do |f| %>
        <p>
        	<% if @task.errors.any? %>
            	<ul>
                	<% @task.errors.full_messages.each do |message| %>
                    	<li style = "color: red">
                        	* <%= message%>
                    	</li>
                	<% end %>
            	</ul>
        		<% end %>
            </p>
            <br>
    		<div class = "field">
    			<div class = "control">
            		<%= f.label :category_id %>
            		<br>
            		<%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), { }, { class: "select" } %>
        		</div>
    		</div>
    		<div class = "field">
        		<div class = "control">
            		<%= f.label :name %>
            		<%= f.text_field :name, class: "input" %>
        		</div>
    		</div>
    		<div class = "field">
        		<div class = "control">
        			<%= f.label :details %>
            		<%= f.text_area :details, class: "textarea", style: "margin: 0px; width:583.6px; height: 100px;" %>
        		</div>
    		</div>
    		<div class = "field">
    			<div class = "control">
        			<%= f.label :deadline %>
        			<br>
        			<%= f.date_field :deadline %>
        		</div>
    		</div>
    		<div class = "field">
        		<%= f.check_box :started %>
        		<%= f.label :started, style: "margin-right: 30px" %>

        		<%= f.check_box :completed %>
        		<%= f.label :completed %>
    		</div>
    
    
    		<div class =  "field">
    			<div class = "control">
            		<%= f.submit :Submit, class: "button is-success" %>
            		
        		</div>
    		</div>
    
		<% end %>

	</div>
</div>
    

app/views/tasks/index.html.erb
<div class = "columns is-centered">
    <div class = "column is-two-thirds">

        <div class = content>
            <h1 class = "is-size-2 has-text-weight-bold mb-3">Tasks</h1>
            
            <br>
            
            <%= link_to 'Create Task', new_category_task_path(@category), class: "button is-info" %>
            
        </div>

        <table class = "table is-striped is-bordered is-fullwidth">
            <thead>
                <tr class="th is-selected">
                    <th>Category</th>
                    <th>Name</th>
                    <th>Details</th>
                    <th>Deadline</th>
                    <th>Started</th>
                    <th>Completed</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>
                <% @tasks.each do |task| %>
                    <% category = Category.find(task.category.id) %>
                    <tr>
                        <td><%= link_to category.name, category_path(@category) %></td>
                        <td><%= link_to task.name, [@category, task] %></td>
                        <td><%= task.details %></td>
                        <td><%= task.deadline %></td>
                        <td><%= task.started %></td>
                        <td><%= task.completed %></td>
                        <td>
                            <div class = "field is-grouped" >
                                <div class = "control">
                                    
                                        <%= link_to 'Edit', edit_category_task_path(@category, task), class: "button is-small is-warning" %>
                                    
                                </div>
                                <div class = "control">
                                    
                                        <%= link_to 'Delete', [@category, task], method: :delete, data: {confirm: "Are you sure?"}, class: "button is-small is-danger" %>
                                    
                                    
                                </div>
                            </div>
                        </td>
                    </tr>
                    
                <% end %>
            </tbody>
        <table>

	</div>
</div>

app/views/tasks/new.html.erb
<div class = "columns is-centered">
    <div class = "column is-half">
        <h1 class = "is-size-2 has-text-weight-bold mb-3">New Task</h1>

		<%= form_with model: [@category, @task], local: true do |f| %>
    		<p>
        		<% if @task.errors.any? %>
            		<ul>
                		<% @task.errors.full_messages.each do |message| %>
                    		<li style = "color: red">
                        		* <%= message%>
                    		</li>
                		<% end %>
            		</ul>
        		<% end %>
            </p>
            <br>
    		<div class = "field">
    			<div class = "control">
            		<%= f.label :category_id %>
            		<br>
            		<%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), { }, { class: "select" } %>
        		</div>
    		</div>
    		<div class = "field">
        		<div class = "control">
            		<%= f.label :name %>
            		<%= f.text_field :name, class: "input" %>
        		</div>
    		</div>
    		<div class = "field">
        		<div class = "control">
        			<%= f.label :details %>
            		<%= f.text_area :details, class: "textarea", style: "margin: 0px; width:583.6px; height: 100px;" %>
        		</div>
    		</div>
    		<div class = "field">
    			<div class = "control">
        			<%= f.label :deadline %>
        			<br>
        			<%= f.date_field :deadline %>
        		</div>
    		</div>
    		<div class = "field">
        		<%= f.check_box :started %>
        		<%= f.label :started, style: "margin-right: 30px" %>

        		<%= f.check_box :completed %>
        		<%= f.label :completed %>
    		</div>
    
    
    		<div class =  "field">
    			<div class = "control">
            		<%= f.submit :Submit, class: "button is-success" %>
            		<%= link_to 'Back', category_tasks_path(@category), class: "button" %>
        		</div>
    		</div>
    
		<% end %>

	</div>
</div>

app/views/tasks/show.html.erb
<div class = "columns is-centered">
    <div class = "column is-half">  
        <h1 class = "is-size-2 has-text-weight-bold mb-3"><%= @task.name %></h1>

        <div class = "content">
            <h2 class = "is-size-3 mb-3"><%= @task.category.name %></h2>
            <br>
            <%= @task.details %>
            <h3 class = "is-size-5 mb-2">Deadline:</h3><%= @task.deadline %>
            <h3 class = "is-size-5 mb-2">Started:</h3><%= @task.started %>
            <h3 class = "is-size-5 mb-2">Completed:</h3><%= @task.completed %>
        </div>

        <%= link_to 'Back to Tasks', category_tasks_path, class: "button" %>
    </div>
</div>

app/views/tasks/today.html.erb
<div class = "columns is-centered">
    <div class = "column is-two-thirds">

        <h1 class = "is-size-2 has-text-weight-bold mb-3">Tasks for Today</h1>

        <div class = "content">

            <% if @tasks_incomplete.length === 0 %>
                <h2 class = "is-size-3 mb-3">All clear!</h2>
                <br>
                <%= link_to 'Categories', categories_path, class: "button" %>
            <% else %>

                <table class = "table is-striped is-bordered is-fullwidth">
                    <thead>
                        <tr class="th is-selected">
                            <th>Category</th>
                            <th>Name</th>
                            <th>Details</th>
                            <th>Deadline</th>
                            <th>Started</th>
                            <th>Completed</th>
                            <th>Actions</th>
                        </tr>
                    </thead>

                    <tbody>
                    
                        <% @tasks_incomplete.each do |task| %>
                            <% category = Category.find(task.category_id) %>
                            <tr>
                                
                                <td><%= link_to category.name, category_path(category.id) %></td>
                                <td><%= link_to task.name, category_task_path(category.id, task.id) %></td>
                                <td><%= task.details %></td>
                                <td><%= task.deadline %></td>
                                <td><%= task.started %></td>
                                <td><%= task.completed %></td>
                                <td>
                                    <div class = "field is-grouped" >
                                        <div class = "control">
                                            <%= link_to 'Edit', edit_category_task_path(category.id, task.id), class: "button is-small is-warning" %>
                                        </div>
                                        <div class = "control">
                                            <%= link_to 'Delete', category_task_path(category.id, task.id), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-small is-danger" %>
                                        </div>
                                        
                                    </div>
                                </td>
                                
                            </tr>

                        <% end %>

                            
                    </tbody>
                <table>
            <% end %>
        </div>
    </div>
</div>